CREATE TABLE IF NOT EXISTS tb_usuario (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_rol (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    nombre VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tb_moneda (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tb_tipo_cambio (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo_cambio DECIMAL(10,2) NOT NULL,
    id_moneda_origen BIGINT NOT NULL,
    id_moneda_destino BIGINT NOT NULL
);
